apiVersion: extension.argoproj.io/v1
kind: ArgoCDExtension
metadata:
  name: rollouts-ui-extension
  namespace: argocd
spec:
  extends: ui
  target:
    resource:
      group: argoproj.io
      kind: Rollout
  source:
    file: https://github.com/rbreeze/rollout-extension/releases/download/v0.2/extensions.js
